/*
	JIPJiraSoapServiceServiceExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@interface JIPJiraSoapServiceServiceExample : NSObject {
}
-(void)run;
@end
		