/*
	JiraSoapServiceServiceExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@class JiraSoapServiceService;
@interface JiraSoapServiceServiceExample : NSObject {
	JiraSoapServiceService* service;
}
-(void)run;
@end
		